### ISSUE TITLE
Problem uploading maf

### ISSUE THREAD

**Issue by avrahamgr** [marcos-diazg/musica#34]
Hello,
I tried uploading a full maf file, but naturally this was too big. I then cut out only the first sample, and recieved a non-specified error. File type seemed fine.
Any ideas what I can try?
Thanks so much,
Avi

**Comment by marcos-diazg** [comment]
Hello!

First of all thank you for using our app and sorry for the delay! It is a strange error, since I had performed analysis with cutted maf files and everything worked fine. However, it would be great if you could share with me the original and the cutted maf files in order to find a solution. My mail is [diaz2@clinic.cat](mailto:diaz2@clinic.cat).

I love to learn about this kind of issues and try to help as much as possible in using our application. So, thanks for this opportunity!
