### ISSUE TITLE
Error running R app

### ISSUE THREAD

**Issue by mwi468** [marcos-diazg/musica#36]
Hi, 

Thank you for developing such a useful tool. I am trying to analyze mutation signatures using somatic data downloaded from TCGA in the maf format. I realized that the files were too loarge for the web app and have installed the R app but after I select my maf files for analysis, I get errors.

Specifically I am getting:

Warning: Error in scanBcfHeader: no 'header' line "#CHROM POS ID..."?
Warning: Error in if: argument is of length zero
Warning: Error in round: non-numeric argument to mathematical function

The maf files are the raw files from the TCGA, so do I have to do any manipulation or changes before uploading them in the app for analysis

Thanks, would appreciate your feedback

**Comment by marcos-diazg** [comment]
Hi!

First of all, thanks so much for using our app. Regarding your question, can you share with me the maf files you have downloaded from TCGA in order to find a solution? I'm not sure what is going on. It could be due to some dependencies changes in newer versions or also to upgrades in the MAF format. We will try to find a quick solution.

Thanks for letting me know!

**Comment by mwi468** [comment]
Yes Thank you,
That would be very helpful. 
Couud I have your email to share the files, since they are greater than 10 MB and I am unable to share it on githb. I will just email you a link for my shared dropbox folder

**Comment by marcos-diazg** [comment]
For dropbox is better to use my gmail: m.diaz.gay@gmail.com. Thanks!

**Comment by mwi468** [comment]
Okay thanks I have shared the folder with the files, most of the files are in unzipped format directly from the TCGA and the two unzipped lung cancer MAF files, I was using for analysis

**Comment by marcos-diazg** [comment]
Hi again, I have tested your MAF files and they worked using the specific R version and dependencies specified in the session info I added to the README in 1111aeca186a92614498718c4d70ac4a108aa9ea. This configuration is the same that is present in our web server. In this case the problem is that our server is currently limited to a maximum of 20 samples.

Hope that helps and thanks for your confidence and feedback!

**Comment by mwi468** [comment]
Hi Marcos

I decided to use extractsignatures tool available in MAFtools because I
wanted to continue using R version 3.6 due to some of the other packages in
my pipeline.
I have yet to try the dependencies and packages fthat you had provided for
R 3.4 version and was wondering what would be some of the advantages of
using MuSiCa Vs. the
extracSignatures tool that is part of MAftools
https://www.rdocumentation.org/packages/maftools/versions/0.99.30/topics/extractSignatures


Thanks

**Comment by marcos-diazg** [comment]
Hi!

In this case the extractSignatures function of MAFtools allows you to extract a _de novo_ bunch of signatures implicated in the mutational patterns of your samples. However, this approach doesn't allow you to reconstruct your samples using a collection of well-established signatures as it is the case of our MuSiCa application. These are two completely different scenarios. For a more comprehensive explanation you can look at these two recent reviews: [Baez-Ortega and Gori, 2019](https://doi.org/10.1093/bib/bbx082) and [Grolleman and Díaz-Gay et al, 2019](https://doi.org/10.1016/j.mam.2019.05.002).
