### ISSUE TITLE
Only somatic mutations and SNVs are supposed to be present in the VCF file?

### ISSUE THREAD

**Issue by gprashant123** [marcos-diazg/musica#39]
I have a VCF file generated using Mutect2 and filtered using FilterMutectCalls (GATK). It contains all types of mutations (somatic, germline, SNVs, insertions/deletions) and they are labelled. In order to perform a mutational signature analysis using musica, should the germline and indel mutations be filtered out and only SNVs should be given as input? 

Also, since I am working on RNA-seq data, would choosing Whole exome sequencing option work?

**Comment by marcos-diazg** [comment]
Hello @gprashant123. Sorry for my super late reply, I was finishing my PhD thesis linked with this MuSiCa application. I hope you was able to solve your issue. Just to let you know, indel mutations will be removed automatically by the application. However MuSiCa cannot differentiate between germline and somatic mutation. Therefore, if you want to perform an analysis only for somatic mutations you should remove previously all germline variants. Regarding study type, it is used to calculate the number of bases sequenced in order to better estimate tumor mutational burden / somatic mutational prevalence.

Hope this helps. Sorry again for the delay.

**Comment by gprashant123** [comment]
Thanks for letting me know, I raised this issue when I was doing my summer research intern on analyzing RNA-seq data. Although I found out alternate ways at that time, I would definitely be looking forward to use MuSiCa in the future.
