### ISSUE TITLE
Maf file with multiple samples

### ISSUE THREAD

**Issue by breezyzhao** [marcos-diazg/musica#46]
Hi,

I am running the Musica locally and it always failed when I try to upload a TCGA maf files. (tsv files works well)
Just curious, is there a template maf file I can use to modify the TCGA maf files?

Thank you.
Xin

**Comment by marcos-diazg** [comment]
Hey Xin! 

Thanks so much for your interest. Unless TCGA maf format has changed recently, it should work properly. Could you please let me know which maf files you are trying to use?

Best,

Marcos

**Comment by breezyzhao** [comment]
Hi Macros,

Thanks for the response.

We use the maf file from TCGA FireBrowse.

I also attached one cancer type "UVM" with dropbox link: https://www.dropbox.com/sh/0wtje0xzwvfqyw9/AAAyPbWTnUl8iyB_88cjRxBxa?dl=0

Let me know if it works

Thank you.
Xin

**Comment by marcos-diazg** [comment]
Dear Xin,

I'm really sorry for the late reply. I hope it can still be helpful. The error is due to the fact that the MAF files from FireBrowse have a column named `Start_position` instead of the commonly used `Start_Position`.

We are no longer updating MuSiCa since we are preparing a new tool that should be available in the next few months, where we will fix this issue.

Thanks so much again for your interest and help.

Marcos
